language: cpp
compiler:
- clang
- gcc
os:
- osx
addons:
  homebrew:
    packages:
    - cmake
    - eigen
    - qt
script:
- cmake -DUNBLENDING_BUILD_CLI_APP=ON -DUNBLENDING_BUILD_GUI_APP=ON . && make
