language: cpp
compiler:
- clang
- gcc
os:
- linux
- osx
dist: xenial
addons:
  homebrew:
    packages:
    - eigen
    - qt
    update: true
  apt:
    packages:
    - qt5-default
    - libeigen3-dev
script:
- cmake -DUNBLENDING_BUILD_CLI_APP=ON -DUNBLENDING_BUILD_GUI_APP=ON . && make
